            - name: Clasp Action
  # You may pin to the exact commit or the version.
  # uses: daikikatsuragawa/clasp-action@861a8749051d74579044acc6234eb3a71db2baa2
  uses: daikikatsuragawa/clasp-action@v1.2.0
  with:
    # access_token written in .clasprc.json
    accessToken: 
    # id_token written in .clasprc.json
    idToken: 
    # refresh_token written in .clasprc.json
    refreshToken: 
    # clientId written in .clasprc.json
    clientId: 
    # clientSecret written in .clasprc.json
    clientSecret: 
    # scriptId written in .clasp.json
    scriptId: 
    # Directory where scripts are stored
    rootDir: # optional
    # Command to execute(push or deploy)
    command: 
    # Description of the deployment
    description: # optional
    # Deploy ID that will be updated
    deployId: # optional
          
